name: Manual Approval Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run initial tasks
      run: |
        echo "Running initial tasks..."
        # Aquí puedes poner el código que necesitas ejecutar antes de la intervención

    - name: Request manual approval
      uses: actions/stale@v3.0.19
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        stale-issue-message: 'Manual approval required'
        days-before-stale: 0
        days-before-close: -1
        only-labels: approval

    - name: Pause for manual approval
      uses: actions/wait-for-approval@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPROVAL_LABEL: 'approved'

    - name: Continue after approval
      if: success()
      run: |
        echo "Continuing the workflow after manual approval."
        # Aquí puedes poner el código que necesitas ejecutar después de la intervención
