name: Manual Approval Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run initial tasks
      run: |
        echo "Running initial tasks..."
        # Aquí puedes poner el código que necesitas ejecutar antes de la intervención

    - name: Request approval
      run: echo "Requesting manual approval..."
      environment: manual-approval

  continue:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Continue after approval
      run: |
        echo "Continuing the workflow after manual approval."
        # Aquí puedes poner el código que necesitas ejecutar después de la intervención
