name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
            fetch-depth: 0
      - run: |
          echo ${{ github.event.client_payload.github.actor }}
          echo ${{ github.event.client_payload.github.action }}
