name: Manual Approval Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run initial tasks
      run: |
        echo "Running initial tasks..."
        # Aquí puedes poner el código que necesitas ejecutar antes de la intervención

    - name: Pause for manual intervention
      id: pause
      run: |
        echo "Manual intervention required. Please approve to continue."
        echo "::notice::Pause for manual intervention. Please approve to continue."
        echo "::set-output name=status::paused"

    - name: Wait for approval
      if: steps.pause.outputs.status == 'paused'
      run: |
        echo "Waiting for manual approval..."
        # Espera activa simulada (10 minutos)
        sleep 600

    - name: Continue after approval
      if: steps.pause.outputs.status == 'paused'
      run: |
        echo "Continuing the workflow after manual approval."
        # Aquí puedes poner el código que necesitas ejecutar después de la intervención

