name: Manual Approval Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run initial tasks
      run: |
        echo "Running initial tasks..."
        # Aquí puedes poner el código que necesitas ejecutar antes de la intervención

    - name: Request approval
      run: |
        echo "Requesting manual approval..."
        echo "::pause::Awaiting manual approval"

  manual_approval:
    needs: build
    runs-on: ubuntu-latest
    environment: manual-approval

    steps:
    - name: Approval granted
      run: echo "Manual approval granted, resuming workflow..."
