name: Code Review with GPT

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read
  actions: read

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.1.10
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-3.5-turbo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
