name: GPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0
          
      - name: git-diff-action
        uses: GrantBirki/git-diff-action@v2.7.0 # A github action for gathering the git diff of our pull request
        id: git-diff
        with:
          raw_diff_file_output: diff.txt
          file_output_only: "true" #Makes us exclude printing the diff on the console for security purposes

      - name: Perfom Code Review With gpt-4
        id: code_review_suggestions
        run: |
          # Get the code changes
          changed_code=$(cat ${{steps.git-diff.outputs.raw-diff-path}})
          
          echo "PR Changes $changed_code"
          
          # Escape newlines and double quotes in the changed_code
          escaped_code=$(echo "$changed_code" | jq -s -R -r @json)
          
          response=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d "{
              \"model\": \"gpt-4\",
              \"messages\": [
                { \"role\": \"system\", \"content\": \"${{ vars.CODE_REVIEW_PROMPT }}\" },
                { \"role\": \"user\", \"content\": $escaped_code }
              ]
            }")
          
          echo "This is the response $response"
          
          code_review_suggestions=$(echo "$response" | jq -r '.choices[0].message.content')
          
          echo "$code_review_suggestions" > code_suggestions.txt
