# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Serenity Tests in GitHub

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Prueba a correr"
        required: true
        default: 'RunnerAllFeatures'
        type: choice
        options:
          - RunnerAllFeatures
          - RunCreateAccountFeature
          - RunEditAccountFeature

      tags_in_scenario:
        description: "Desea ejecutar con tags"
        required: true
        type: boolean

      runnerTag:
        description: "Prueba a correr"
        required: true
        default: 'create'
        type: choice
        options:
          - create
          - edit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      #- name: Build and create cache directory
        #run: mvn dependency:go-offline

      - name: Run browser
        uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      
      - name: Build with Maven if tags_in_scenario is true
        if: ${{ inputs.tags_in_scenario }}
        run: mvn clean verify -Dtest=${{ inputs.runner }} serenity:aggregate serenity:check

      

  runner_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
              
      - name: Build with Maven if tags_in_scenario is true
        if: ${{ inputs.tags_in_scenario }}
        run: mvn clean verify -Dtest=${{ inputs.runner }} serenity:aggregate serenity:check
        
      - name: Build with Maven with tags if tags_in_scenario is false
        if: ${{ !inputs.tags_in_scenario }}
        run: mvn clean verify -Dtags=${{ inputs.runnerTag }} serenity:aggregate serenity:check

      - name: Test Report Generation
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Serenity Report
          path: target/site/serenity/


    
    
          
